import type { GuidelineRule, RestrictionDef } from "./types";

export const HOTEL_GROUPS = [
  "Central-North Europe",
  "Western Europe",
  "Southern Europe",
  "Eastern Europe",
];

// Used on the new restriction form — different dataset from the list page
export const NEW_FORM_HOTEL_GROUPS = ["00327803", "B&B Hotels", "Luxury Collection"];

export const SEGMENTS = ["OTA - Transient", "Corporate", "Leisure"];
export const ROOM_TYPES = ["All Room Types", "Standard", "Deluxe", "Suite"];
export const STRATEGY_FOR_OPTIONS = ["Property", "Yield Segments", "Sub Rates", "Room Type"];
export const MOCK_SUB_RATES = [
  "Advance Purchase 7",
  "Advance Purchase 14",
  "Non-Refundable",
  "Breakfast Package",
  "Weekend Escape",
];
export const YIELD_SEGMENTS = ["OTA - Transient", "Corporate", "Leisure", "Government", "Group"];
export const FORM_ROOM_TYPES = ["All Room Types", "Standard", "Deluxe", "Suite", "Junior Suite", "Penthouse"];

export const RESTRICTIONS: RestrictionDef[] = [
  { key: "CTS", label: "Closed to Stay", hasValue: false },
  { key: "CTA", label: "Closed to Arrival", hasValue: false },
  { key: "CTD", label: "Closed to Departure", hasValue: false },
  { key: "MinST", label: "Min Stay Thru", hasValue: true },
  { key: "MaxST", label: "Max Stay Thru", hasValue: true },
  { key: "MinSA", label: "Min Stay Arrival", hasValue: true },
  { key: "MaxSA", label: "Max Stay Arrival", hasValue: true },
];

export const MOCK_PROPERTIES_BY_GROUP: Record<string, { name: string; existingStrategies: number }[]> = {
  "Central-North Europe": [
    { name: "Grand Hotel Amsterdam", existingStrategies: 4 },
    { name: "Berlin Mitte Suites", existingStrategies: 2 },
    { name: "Copenhagen Plaza", existingStrategies: 6 },
    { name: "Stockholm Harbour Inn", existingStrategies: 1 },
  ],
  "Western Europe": [
    { name: "Paris Champs Élysées", existingStrategies: 3 },
    { name: "Madrid Gran Via Hotel", existingStrategies: 5 },
    { name: "Lisbon Heritage Hotel", existingStrategies: 0 },
  ],
  "Southern Europe": [
    { name: "Rome Pantheon Suites", existingStrategies: 7 },
    { name: "Athens Acropolis Hotel", existingStrategies: 2 },
    { name: "Barcelona Ramblas", existingStrategies: 4 },
  ],
  "Eastern Europe": [
    { name: "Warsaw Old Town Hotel", existingStrategies: 1 },
    { name: "Prague Castle Inn", existingStrategies: 3 },
    { name: "Budapest Danube View", existingStrategies: 5 },
  ],
};

export const MOCK_RULES: GuidelineRule[] = [
  // ── Central-North Europe ─────────────────────────────────────────────────────
  {
    id: "1",
    name: "Summer Weekend Min Stay",
    hotelGroup: "Central-North Europe",
    granularity: "segment",
    segment: "OTA - Transient",
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 2 }],
    stayDate: "Jun 1 – Aug 31, 2026 (Fri–Sun)",
    criteria: "Everyday",
    created: "Sophie Laurent at 4/9/2026",
    active: true,
  },
  {
    id: "2",
    name: "Holiday Closure",
    hotelGroup: "Central-North Europe",
    granularity: "property",
    segment: "Property",
    roomType: "All Room Types",
    restrictions: [{ type: "CTA" }, { type: "CTD" }],
    stayDate: "Dec 23 – Jan 2, 2026 (All days)",
    criteria: "Everyday",
    created: "Marcus Weber at 4/9/2026",
    active: true,
  },
  {
    id: "3",
    name: "Low Demand Minimum",
    hotelGroup: "Central-North Europe",
    granularity: "segment",
    segment: "Leisure",
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 1 }],
    stayDate: "Nov 1 – Nov 30, 2026 (Mon–Wed)",
    criteria: "Demand occupancy < 50%",
    created: "James Thornton at 4/10/2026",
    active: true,
  },
  {
    id: "7",
    name: "Corporate Extended Stay Cap",
    hotelGroup: "Central-North Europe",
    granularity: "segment",
    segment: "Corporate",
    roomType: "All Room Types",
    restrictions: [{ type: "MaxST", value: 14 }],
    stayDate: "Jan 1 – Dec 31, 2026 (All days)",
    criteria: "Everyday",
    created: "Marcus Weber at 4/14/2026",
    active: true,
  },
  {
    id: "15",
    name: "Advance Purchase Min Stay",
    hotelGroup: "Central-North Europe",
    granularity: "subrate",
    segment: "Advance Purchase 7",
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 2 }],
    stayDate: "Jun 1 – Aug 31, 2026 (All days)",
    criteria: "Everyday",
    created: "Sophie Laurent at 4/20/2026",
    active: true,
  },
  // ── Western Europe ───────────────────────────────────────────────────────────
  {
    id: "4",
    name: "Conference Block Q1",
    hotelGroup: "Western Europe",
    granularity: "segment",
    segment: "Corporate",
    roomType: "All Room Types",
    restrictions: [{ type: "CTS" }],
    stayDate: "Jan 15 – Jan 20, 2026 (Mon–Thu)",
    criteria: "Everyday",
    created: "Elena Rossi at 4/10/2026",
    active: false,
  },
  {
    id: "5",
    name: "Peak Season Max Stay",
    hotelGroup: "Western Europe",
    granularity: "segment",
    segment: "OTA - Transient",
    roomType: "All Room Types",
    restrictions: [{ type: "MaxSA", value: 7 }],
    stayDate: "Jul 1 – Aug 31, 2026 (All days)",
    criteria: "Everyday",
    created: "Ana Rodrigues at 4/11/2026",
    active: true,
  },
  {
    id: "8",
    name: "Shoulder Season Arrival Restriction",
    hotelGroup: "Western Europe",
    granularity: "property",
    segment: "Property",
    roomType: "All Room Types",
    restrictions: [{ type: "CTA" }],
    stayDate: "Oct 1 – Nov 30, 2026 (Sun)",
    criteria: "Demand occupancy < 40%",
    created: "Ana Rodrigues at 4/15/2026",
    active: true,
  },
  {
    id: "9",
    name: "Leisure Weekend Min Stay",
    hotelGroup: "Western Europe",
    granularity: "segment",
    segment: "Leisure",
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 2 }],
    stayDate: "Apr 1 – Jun 30, 2026 (Fri–Sat)",
    criteria: "Everyday",
    created: "Elena Rossi at 4/15/2026",
    active: true,
  },
  {
    id: "16",
    name: "Non-Refundable Low Season Closure",
    hotelGroup: "Western Europe",
    granularity: "subrate",
    segment: "Non-Refundable",
    roomType: "All Room Types",
    restrictions: [{ type: "CTA" }, { type: "CTD" }],
    stayDate: "Jan 4 – Mar 14, 2026 (All days)",
    criteria: "Everyday",
    created: "Elena Rossi at 4/20/2026",
    active: true,
  },
  // ── Southern Europe ──────────────────────────────────────────────────────────
  {
    id: "6",
    name: "Year-Round Weekend Closure",
    hotelGroup: "Southern Europe",
    granularity: "property",
    segment: "Property",
    roomType: "All Room Types",
    restrictions: [{ type: "CTS" }],
    stayDate: "Jan 1 – Dec 31, 2026 (Sat–Sun)",
    criteria: "Everyday",
    created: "Thomas Müller at 4/12/2026",
    active: false,
  },
  {
    id: "10",
    name: "High Season Min Stay",
    hotelGroup: "Southern Europe",
    granularity: "segment",
    segment: "OTA - Transient",
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 3 }],
    stayDate: "Jul 1 – Sep 30, 2026 (All days)",
    criteria: "Demand occupancy > 70%",
    created: "Thomas Müller at 4/16/2026",
    active: true,
  },
  {
    id: "11",
    name: "Off-Season Corporate Max",
    hotelGroup: "Southern Europe",
    granularity: "segment",
    segment: "Corporate",
    roomType: "All Room Types",
    restrictions: [{ type: "MaxSA", value: 5 }],
    stayDate: "Nov 1 – Feb 28, 2026 (Mon–Fri)",
    criteria: "Everyday",
    created: "Sofia Carvalho at 4/16/2026",
    active: true,
  },
  {
    id: "17",
    name: "Breakfast Package Weekend Min Stay",
    hotelGroup: "Southern Europe",
    granularity: "subrate",
    segment: "Breakfast Package",
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 2 }],
    stayDate: "Apr 1 – Oct 31, 2026 (Fri–Sun)",
    criteria: "Everyday",
    created: "Sofia Carvalho at 4/20/2026",
    active: true,
  },
  {
    id: "18",
    name: "Multi-Segment Peak Season",
    hotelGroup: "Western Europe",
    granularity: "segment",
    segment: "OTA - Transient",
    segments: ["OTA - Transient", "Leisure", "Corporate"],
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 3 }],
    stayDate: "Jul 1 – Aug 31, 2026 (All days)",
    criteria: "Demand occupancy > 75%",
    created: "Ana Rodrigues at 5/2/2026",
    active: true,
  },
  {
    id: "19",
    name: "Multi-Rate Early Booking",
    hotelGroup: "Southern Europe",
    granularity: "subrate",
    segment: "Advance Purchase 7",
    segments: ["Advance Purchase 7", "Advance Purchase 14"],
    roomType: "All Room Types",
    restrictions: [{ type: "MinSA", value: 2 }],
    stayDate: "Jun 1 – Sep 30, 2026 (Fri–Sun)",
    criteria: "Everyday",
    created: "Sofia Carvalho at 5/2/2026",
    active: true,
  },
  {
    id: "20",
    name: "Suite & Deluxe Closure",
    hotelGroup: "Eastern Europe",
    granularity: "roomtype",
    segment: "Property",
    roomType: "Suite",
    roomTypes: ["Suite", "Junior Suite", "Deluxe"],
    restrictions: [{ type: "CTA" }],
    stayDate: "Dec 23 – Jan 2, 2027 (All days)",
    criteria: "Everyday",
    created: "Piotr Nowak at 5/2/2026",
    active: true,
  },
  // ── Eastern Europe ───────────────────────────────────────────────────────────
  {
    id: "12",
    name: "New Year Closure",
    hotelGroup: "Eastern Europe",
    granularity: "property",
    segment: "Property",
    roomType: "All Room Types",
    restrictions: [{ type: "CTD" }],
    stayDate: "Dec 31, 2026 – Jan 1, 2027 (All days)",
    criteria: "Everyday",
    created: "Piotr Nowak at 4/17/2026",
    active: true,
  },
  {
    id: "13",
    name: "Spring OTA Min Stay",
    hotelGroup: "Eastern Europe",
    granularity: "segment",
    segment: "OTA - Transient",
    roomType: "All Room Types",
    restrictions: [{ type: "MinST", value: 2 }],
    stayDate: "Mar 1 – May 31, 2026 (Fri–Sun)",
    criteria: "Everyday",
    created: "Piotr Nowak at 4/17/2026",
    active: true,
  },
  {
    id: "14",
    name: "Leisure Suite Restriction",
    hotelGroup: "Eastern Europe",
    granularity: "roomtype",
    segment: "Property",
    roomType: "Suite",
    restrictions: [{ type: "MinSA", value: 2 }, { type: "MaxSA", value: 7 }],
    stayDate: "Jun 1 – Aug 31, 2026 (All days)",
    criteria: "Demand occupancy > 60%",
    created: "Katarzyna Wiśniewska at 4/18/2026",
    active: false,
  },
];
